language: python
python:
    - 2.7
    - 2.6
install:
    - source utils/init-environment
    - pip install codecov
services:
    - elasticsearch
# This is required for elasticsearch
before_script:
    - sleep 10
script: coverage run --source shelf/ -m unittest discover -p *_test.py tests -b
after_success:
    - codecov
notifications:
    email:
        recipients:
            - andygertjejansen@outlook.com
            - uilwen@gmail.com
