language: python
python:
    - 2.7
    - 2.6
install:
    - source utils/init-environment
    - pip install codecov
script: pyproctor
services:
    - elasticsearch
# This is required for elasticsearch
before_script:
    - sleep 10
after_success:
    - codecov
