language: python
python:
    - 2.7
    - 2.6
install:
    - source utils/init-environment
    - pip install codecov
script: coverage run --source pyshelf/ -m unittest discover -p *_test.py tests -b
after_success:
    - codecov
